In [350]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [351]:
data = pd.read_csv('Dataset_food.csv')
data.drop(columns=['Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15'], inplace=True)

In [352]:
data

Buổi      Cảm xúc  Độ tuổi  Số lượng người Thời tiết Phong cách ẩm thực   
0     Sáng          Vui       10               5      Lạnh         Trung quốc  \
1     Trưa  Bình thường       21               3      Nóng           Việt nam   
2    Chiều     Khó chịu       12               3  Hơi lạnh           miền nam   
3     Sáng          Vui       23               2  Quá Nóng           hàn quốc   
4      Đêm  Bình thường       10               2       Mát     Món cho trẻ em   
..     ...          ...      ...             ...       ...                ...   
992  Chiều         Buồn       35               5      Nóng     Món cho trẻ em   
993   Trưa     Khó chịu       15               2  Qúa lạnh          đồ ăn vặt   
994    Đêm         Buồn       11               1       Mát           Việt nam   
995  Chiều     Khó chịu       16               5      Nóng     Món cho trẻ em   
996   Trưa         Buồn       16               2  Quá Nóng           miền nam   

       Loại hình quán ăn     Chế độ ăn                  Đặc Biệt  Độ phổ biến   
0    Nhà Hàng Sang Trọng  ăn thoải mái              có chỗ đỗ xe    hot trend  \
1            Quán Vỉa Hè       ăn chay        có phòng trông trẻ      đặc sản   
2      Nhà hàng bình dân      ăn kiêng        có phòng hút thuốc   bestseller   
3            Quán Vỉa Hè  ăn thoải mái             Đang giảm giá  bình thường   
4    Nhà Hàng Sang Trọng       ăn chay  có không gian ngoài trời    hot trend   
..                   ...           ...                       ...          ...   
992    Nhà hàng bình dân      ăn kiêng        có phòng trông trẻ      đặc sản   
993          Quán Vỉa Hè       ăn chay             wifi miễn phí   bestseller   
994    Nhà hàng bình dân      ăn kiêng             Đang giảm giá  bình thường   
995  Nhà Hàng Sang Trọng       ăn chay             wifi miễn phí    hot trend   
996  Nhà Hàng Sang Trọng      ăn kiêng             wifi miễn phí   bestseller   

          Loại đồ ăn  
0           Món nước  
1           Món lạnh  
2    Món Tráng miệng  
3    Món Tráng miệng  
4           Món lạnh  
..               ...  
992        đồ ăn vặt  
993         Món nước  
994  Món Tráng miệng  
995        đồ ăn vặt  
996   Món cho trẻ em  

[997 rows x 11 columns]

In [353]:
column = data.columns

In [354]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 997 entries, 0 to 996
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Buổi                997 non-null    object
 1   Cảm xúc             997 non-null    object
 2   Độ tuổi             997 non-null    int64 
 3   Số lượng người      997 non-null    int64 
 4   Thời tiết           997 non-null    object
 5   Phong cách ẩm thực  997 non-null    object
 6   Loại hình quán ăn   997 non-null    object
 7   Chế độ ăn           997 non-null    object
 8   Đặc Biệt            997 non-null    object
 9   Độ phổ biến         997 non-null    object
 10  Loại đồ ăn          997 non-null    object
dtypes: int64(2), object(9)
memory usage: 85.8+ KB


In [355]:
b = data['Buổi']
# b_category = b.cat.categories.to_list()
b_category_count = b.value_counts(sort=False).to_numpy()
b_category_count

array([220, 208, 204, 176, 189], dtype=int64)

In [356]:
import plotly.express as px
fig = px.histogram(data, x='Buổi', color='Buổi', title='Buổi Distribution')
fig.update_layout(xaxis_title='Buổi', yaxis_title='Count')
fig.show()

In [357]:
fig = px.histogram(data, x='Cảm xúc', color='Cảm xúc', title='Cảm xúc Distribution')
fig.update_layout(xaxis_title='Cảm xúc', yaxis_title='Count')
fig.show()

In [358]:
fig = px.histogram(data, x='Thời tiết', color='Thời tiết', title='Thời tiết Distribution')
fig.update_layout(xaxis_title='Buổi', yaxis_title='Count')
fig.show()

In [359]:
fig = px.histogram(data, x='Phong cách ẩm thực', color='Phong cách ẩm thực', title='Phong cách ẩm thực Distribution')
fig.update_layout(xaxis_title='Phong cách', yaxis_title='Count')
fig.show()

In [360]:
fig = px.histogram(data, x='Loại hình quán ăn', color='Loại hình quán ăn', title='Buổi Distribution')
fig.update_layout(xaxis_title='Buổi', yaxis_title='Count')
fig.show()

In [361]:
fig = px.histogram(data, x='Chế độ ăn', color='Chế độ ăn', title='Buổi Distribution')
fig.update_layout(xaxis_title='Buổi', yaxis_title='Count')
fig.show()

In [362]:
fig = px.histogram(data, x='Đặc Biệt', color='Đặc Biệt', title='Buổi Distribution')
fig.update_layout(xaxis_title='Buổi', yaxis_title='Count')
fig.show()

In [363]:
fig = px.histogram(data, x='Độ phổ biến', color='Độ phổ biến', title='Buổi Distribution')
fig.update_layout(xaxis_title='Buổi', yaxis_title='Count')
fig.show()

In [364]:
fig = px.histogram(data, x='Loại đồ ăn', color='Loại đồ ăn', title='Buổi Distribution')
fig.update_layout(xaxis_title='Buổi', yaxis_title='Count')
fig.show()

In [365]:
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

In [366]:
X

Buổi      Cảm xúc  Độ tuổi  Số lượng người Thời tiết Phong cách ẩm thực   
0     Sáng          Vui       10               5      Lạnh         Trung quốc  \
1     Trưa  Bình thường       21               3      Nóng           Việt nam   
2    Chiều     Khó chịu       12               3  Hơi lạnh           miền nam   
3     Sáng          Vui       23               2  Quá Nóng           hàn quốc   
4      Đêm  Bình thường       10               2       Mát     Món cho trẻ em   
..     ...          ...      ...             ...       ...                ...   
992  Chiều         Buồn       35               5      Nóng     Món cho trẻ em   
993   Trưa     Khó chịu       15               2  Qúa lạnh          đồ ăn vặt   
994    Đêm         Buồn       11               1       Mát           Việt nam   
995  Chiều     Khó chịu       16               5      Nóng     Món cho trẻ em   
996   Trưa         Buồn       16               2  Quá Nóng           miền nam   

       Loại hình quán ăn     Chế độ ăn                  Đặc Biệt  Độ phổ biến  
0    Nhà Hàng Sang Trọng  ăn thoải mái              có chỗ đỗ xe    hot trend  
1            Quán Vỉa Hè       ăn chay        có phòng trông trẻ      đặc sản  
2      Nhà hàng bình dân      ăn kiêng        có phòng hút thuốc   bestseller  
3            Quán Vỉa Hè  ăn thoải mái             Đang giảm giá  bình thường  
4    Nhà Hàng Sang Trọng       ăn chay  có không gian ngoài trời    hot trend  
..                   ...           ...                       ...          ...  
992    Nhà hàng bình dân      ăn kiêng        có phòng trông trẻ      đặc sản  
993          Quán Vỉa Hè       ăn chay             wifi miễn phí   bestseller  
994    Nhà hàng bình dân      ăn kiêng             Đang giảm giá  bình thường  
995  Nhà Hàng Sang Trọng       ăn chay             wifi miễn phí    hot trend  
996  Nhà Hàng Sang Trọng      ăn kiêng             wifi miễn phí   bestseller  

[997 rows x 10 columns]

In [367]:
y

0             Món nước
1             Món lạnh
2      Món Tráng miệng
3      Món Tráng miệng
4             Món lạnh
            ...       
992          đồ ăn vặt
993           Món nước
994    Món Tráng miệng
995          đồ ăn vặt
996     Món cho trẻ em
Name: Loại đồ ăn, Length: 997, dtype: object

In [368]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder

# ct0 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0, 1, 4, 5, 6, 7, 8, 9])], remainder='passthrough') 
# X = ct0.fit_transform(X)



In [369]:
def preprocessing(data):
    data['Buổi'] = data['Buổi'].apply(lambda x: 0 if x == 'Sáng' 
                                                else (1 if x == 'Trưa'
                                                else (2 if x == 'Chiều'
                                                else (3 if x == 'Tối'
                                                else 4))))
    data['Cảm xúc'] = data['Cảm xúc'].apply(lambda x: 0 if x == 'Vui'
                                                else (1 if x == 'Buồn'
                                                else (2 if x == 'Khó chịu'
                                                else 3)))
    data['Thời tiết'] = data['Thời tiết'].apply(lambda x: 0 if x == 'Lạnh' or x == 'Hơi lạnh' or x == 'Qúa lạnh'
                                                else (1 if x == 'Nóng' or x == 'Hơi nóng' or x == 'Quá nóng'
                                                else 2))
    data['Phong cách ẩm thực'] = data['Phong cách ẩm thực'].apply(lambda x: 0 if x == 'Trung quốc' 
                                                else (1 if x == 'hàn quốc'
                                                else (2 if x == 'Món cho trẻ em'
                                                else (3 if x == 'đồ ăn vặt'
                                                else (4 if x == 'miền nam'
                                                else 5)))))
    data['Loại hình quán ăn'] = data['Loại hình quán ăn'].apply(lambda x: 0 if x == 'Quán Vỉa Hè'
                                                else (1 if x == 'Nhà hàng bình dân'
                                                else 2))
    data['Chế độ ăn'] = data['Chế độ ăn'].apply(lambda x: 0 if x == 'ăn kiêng'
                                                else (1 if x == 'ăn chay'
                                                else 2))
    data['Đặc Biệt'] = data['Đặc Biệt'].apply(lambda x: 0 if x == 'có chỗ đỗ xe'
                                                else (1 if x == 'có phòng trông trẻ'
                                                else (2 if x == 'có phòng hút thuốc'
                                                else (3 if x == 'Đang giảm giá'
                                                else (4 if x == 'có không gian ngoài trời'
                                                else (5 if x == 'wifi miễn phí'
                                                else 6))))))
    data['Độ phổ biến'] = data['Độ phổ biến'].apply(lambda x: 0 if x == 'hot trend'
                                                else (1 if x == 'đặc sản'
                                                else (2 if x == 'bestseller'
                                                else 3)))

preprocessing(X)


In [370]:
X

Buổi  Cảm xúc  Độ tuổi  Số lượng người  Thời tiết  Phong cách ẩm thực   
0       0        0       10               5          0                   0  \
1       1        3       21               3          1                   5   
2       2        2       12               3          0                   4   
3       0        0       23               2          2                   1   
4       4        3       10               2          2                   2   
..    ...      ...      ...             ...        ...                 ...   
992     2        1       35               5          1                   2   
993     1        2       15               2          0                   3   
994     4        1       11               1          2                   5   
995     2        2       16               5          1                   2   
996     1        1       16               2          2                   4   

     Loại hình quán ăn  Chế độ ăn  Đặc Biệt  Độ phổ biến  
0                    2          2         0            0  
1                    0          1         1            1  
2                    1          0         2            2  
3                    0          2         3            3  
4                    2          1         4            0  
..                 ...        ...       ...          ...  
992                  1          0         1            1  
993                  0          1         5            2  
994                  1          0         3            3  
995                  2          1         5            0  
996                  2          0         5            2  

[997 rows x 10 columns]

In [371]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [372]:
y.shape

(997,)

# Spliting data

In [373]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [374]:
X_train

Buổi  Cảm xúc  Độ tuổi  Số lượng người  Thời tiết  Phong cách ẩm thực   
743     3        1       10               4          2                   3  \
286     0        2       14               4          2                   0   
165     1        3       34               3          0                   2   
958     1        2       14               4          2                   1   
493     3        1       16               4          0                   5   
..    ...      ...      ...             ...        ...                 ...   
106     4        2       35               2          0                   3   
270     2        0       20               4          0                   4   
860     3        1       40               2          1                   1   
435     2        2       21               5          0                   3   
102     0        2       36               4          2                   5   

     Loại hình quán ăn  Chế độ ăn  Đặc Biệt  Độ phổ biến  
743                  2          1         2            2  
286                  0          2         6            1  
165                  1          0         5            0  
958                  0          1         1            3  
493                  1          2         2            1  
..                 ...        ...       ...          ...  
106                  1          1         6            1  
270                  0          0         5            1  
860                  2          1         4            2  
435                  0          2         0            0  
102                  0          0         2            1  

[797 rows x 10 columns]

In [375]:
from sklearn.tree import DecisionTreeClassifier

d_tree_model = DecisionTreeClassifier()

d_tree_model.fit(X_train, y_train)

DecisionTreeClassifier()

In [376]:
y_pred = d_tree_model.predict(X_test)

In [377]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


print("Confussion Matrix: \n", confusion_matrix(y_test, y_pred),"\n")

print("Classification report according to Test prediction: \n", classification_report(y_test, y_pred))

print ("Accuracy of KNN: %.2f %%" %(100*accuracy_score(y_test, y_pred)))

Confussion Matrix: 
 [[ 5  8  6 11  8]
 [ 6  8  9  9 10]
 [ 8  4  6  6 14]
 [10  7  4 10 12]
 [ 4  5 12  8 10]] 

Classification report according to Test prediction: 
               precision    recall  f1-score   support

           0       0.15      0.13      0.14        38
           1       0.25      0.19      0.22        42
           2       0.16      0.16      0.16        38
           3       0.23      0.23      0.23        43
           4       0.19      0.26      0.22        39

    accuracy                           0.20       200
   macro avg       0.20      0.19      0.19       200
weighted avg       0.20      0.20      0.19       200

Accuracy of KNN: 19.50 %
